#manifest for adding variables to containers

kind: Pod
apiVersion: v1
metadata:
  name: testpod
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["bin/bash", "-c", "while true; do echo hello everyone; sleep 5 ; done"]
      env:
        - name: MYNAME #(key name for environment variableto be used inside the container)
          value: demo #(value)


    - name: c01
      image: ubuntu
      command: ["bin/bash", "-c", "while true; do echo hello everyone; sleep 5 ; done"]
      env:
        - name: MYNAME #(key name for environment variableto be used inside the container)
          value: demo #(value)
